/* Offline-first service worker. PRECACHE is regenerated by `node scripts/build-sw.mjs`. */
const VERSION = "bma-ec9d9d4c5cad";
const PRECACHE = [
  "./",
  "./app.js",
  "./content/architecture.md",
  "./content/arm64.md",
  "./content/artifacts.md",
  "./content/binaries.md",
  "./content/debugging.md",
  "./content/electronics.md",
  "./content/exploitation.md",
  "./content/filesystems.md",
  "./content/forensics.md",
  "./content/foundations.md",
  "./content/hwattacks.md",
  "./content/hwtools.md",
  "./content/interfaces.md",
  "./content/iot.md",
  "./content/memforensics.md",
  "./content/mobile.md",
  "./content/os.md",
  "./content/recovery.md",
  "./content/storage.md",
  "./content/wireless.md",
  "./content/x86.md",
  "./data/glossary.js",
  "./data/modules.js",
  "./data/questions/architecture.js",
  "./data/questions/arm64.js",
  "./data/questions/artifacts.js",
  "./data/questions/binaries.js",
  "./data/questions/debugging.js",
  "./data/questions/electronics.js",
  "./data/questions/exploitation.js",
  "./data/questions/filesystems.js",
  "./data/questions/forensics.js",
  "./data/questions/foundations.js",
  "./data/questions/hwattacks.js",
  "./data/questions/hwtools.js",
  "./data/questions/interfaces.js",
  "./data/questions/iot.js",
  "./data/questions/memforensics.js",
  "./data/questions/mobile.js",
  "./data/questions/os.js",
  "./data/questions/recovery.js",
  "./data/questions/storage.js",
  "./data/questions/wireless.js",
  "./data/questions/x86.js",
  "./icons/apple-touch-icon.png",
  "./icons/favicon-32.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./lab.js",
  "./manifest.webmanifest",
  "./styles.css"
];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
// Stale-while-revalidate for same-origin GETs.
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.open(VERSION).then(async (cache) => {
    const hit = await cache.match(req, { ignoreSearch: true });
    const net = fetch(req).then((res) => { if (res.ok) cache.put(req, res.clone()); return res; }).catch(() => hit || (req.mode === "navigate" ? cache.match("./index.html") : undefined));
    return hit || net;
  }));
});
